# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='since',
            field=models.DateField(auto_now=True),
        ),
    ]
