# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-28 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20171124_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='paging_next',
        ),
        migrations.RemoveField(
            model_name='page',
            name='since',
        ),
    ]
