# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20171129_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
