# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-30 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20171129_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
