# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-18 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20171130_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinsights',
            name='post_paging',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
