# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-26 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_pageinsights_post_paging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageinsights',
            name='post_paging',
        ),
        migrations.AddField(
            model_name='page',
            name='post_paging',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
