# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-27 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20171227_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='since',
        ),
    ]
