# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-27 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_page_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='post_since',
            field=models.DateTimeField(null=True),
        ),
    ]
