# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-08 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_page_post_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='access_token',
            field=models.CharField(blank=True, max_length=18000, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=18000, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='pretty_name',
            field=models.CharField(blank=True, max_length=18000, null=True),
        ),
    ]
