# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-20 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171217_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faceusers.FaceUsers'),
        ),
    ]
