# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-18 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171217_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_paging',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reaction_paging',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
