# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-18 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20171218_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='total_comments',
        ),
    ]
