# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-19 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20171219_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
