# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-08 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20171219_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=18000, null=True),
        ),
    ]
