# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-09 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180308_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='engajamento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_impressions_unique',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='taxa_de_engajamento',
            field=models.IntegerField(default=0),
        ),
    ]
