# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-09 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20180509_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='permalink_url',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
