# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-04 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20180509_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='engajamento',
            new_name='total_comments_stream',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='total_comments',
            new_name='total_comments_toplevel',
        ),
        migrations.RemoveField(
            model_name='post',
            name='taxa_de_engajamento',
        ),
    ]
