# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-17 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paging',
            name='model_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paging',
            name='url',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='paging',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
    ]
