# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-22 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagings', '0002_auto_20171217_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='paging',
            name='cursor_after',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='paging',
            name='cursor_before',
            field=models.CharField(default='', max_length=512),
        ),
    ]
