# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-22 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20171219_1841'),
        ('pagings', '0003_auto_20171222_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paging',
            name='url',
        ),
        migrations.AddField(
            model_name='paging',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
