# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-16 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20171206_1133'),
        ('faceusers', '0001_initial'),
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaction',
            name='type',
            field=models.CharField(default='1', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='faceusers.FaceUsers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reaction',
            name='id',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
