# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-17 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_auto_20171216_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='type',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
