# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-17 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171217_2155'),
        ('faceusers', '0002_auto_20171217_2155'),
        ('reactions', '0003_auto_20171217_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faceusers.FaceUsers'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='id',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
    ]
