# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-20 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceusers', '0002_auto_20171217_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faceusers',
            old_name='post_reactions_anger_total',
            new_name='anger',
        ),
        migrations.RenameField(
            model_name='faceusers',
            old_name='post_reactions_haha_total',
            new_name='haha',
        ),
        migrations.RenameField(
            model_name='faceusers',
            old_name='post_reactions_like_total',
            new_name='like',
        ),
        migrations.RenameField(
            model_name='faceusers',
            old_name='post_reactions_love_total',
            new_name='love',
        ),
        migrations.RenameField(
            model_name='faceusers',
            old_name='post_reactions_sorry_total',
            new_name='sorry',
        ),
        migrations.RenameField(
            model_name='faceusers',
            old_name='post_reactions_wow_total',
            new_name='wow',
        ),
    ]
