# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-20 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceusers', '0003_auto_20171220_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faceusers',
            old_name='anger',
            new_name='post_reactions_anger_total',
        ),
        migrations.RenameField(
            model_name='faceusers',
            old_name='haha',
            new_name='post_reactions_haha_total',
        ),
        migrations.RenameField(
            model_name='faceusers',
            old_name='like',
            new_name='post_reactions_like_total',
        ),
        migrations.RenameField(
            model_name='faceusers',
            old_name='love',
            new_name='post_reactions_love_total',
        ),
        migrations.RenameField(
            model_name='faceusers',
            old_name='sorry',
            new_name='post_reactions_sorry_total',
        ),
        migrations.RenameField(
            model_name='faceusers',
            old_name='wow',
            new_name='post_reactions_wow_total',
        ),
    ]
