# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-22 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceusers', '0005_auto_20171221_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faceusers',
            old_name='post_reactions_sorry_total',
            new_name='post_reactions_sad_total',
        ),
    ]
