# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-26 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceusers', '0007_faceusers_post_reactions_pride_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceusers',
            name='post_reactions_thankful_total',
            field=models.IntegerField(default=0),
        ),
    ]
