# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-08 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faceusers', '0008_faceusers_post_reactions_thankful_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceusers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
